
setwd("H:/THESIS/DATA/MATLAB_CODE/TRAINING_MFCC_W512")

DATASET_A  <- read.csv("TRAINING_A.csv")
DATASET_B <- read.csv("TRAINING_B.csv")
DATASET_C <- read.csv("TRAINING_C.csv")
DATASET_D  <- read.csv("TRAINING_D.csv")
DATASET_F <- read.csv("TRAINING_F.csv")
DATASET_E <- read.csv("TRAINING_E.csv")

DATASET_A <- DATASET_A[-1]
DATASET_B <- DATASET_B[-1]
DATASET_C <- DATASET_C[-1]
DATASET_D <- DATASET_D[-1]
DATASET_E <- DATASET_E[-1]
DATASET_F <- DATASET_F[-1]

setwd("H:/THESIS/DATA/MATLAB_CODE/TRAINING_CLASS")



CLASS_A_ABNORMAL <- read.csv("TRAINING_A_ABNORMAL.csv")
CLASS_A_NORMAL <- read.csv("TRAINING_A_NORMAL.csv")

CLASS_B_ABNORMAL <- read.csv("TRAINING_B_ABNORMAL.csv")
CLASS_B_NORMAL <- read.csv("TRAINING_C_NORMAL.csv")

CLASS_C_ABNORMAL <- read.csv("TRAINING_C_ABNORMAL.csv")
CLASS_C_NORMAL <- read.csv("TRAINING_C_NORMAL.csv")

CLASS_D_ABNORMAL <- read.csv("TRAINING_D_ABNORMAL.csv")
CLASS_D_NORMAL <- read.csv("TRAINING_D_NORMAL")

CLASS_E_ABNORMAL <- read.csv("TRAINING_E_ABNORMAL.csv")
CLASS_E_NORMAL <- read.csv("TRAINING_E_NORMAL.csv")

CLASS_F_ABNORMAL<- read.csv("TRAINING_F_ABNORMAL.csv")
CLASS_F_NORMAL <- read.csv("TRAINING_F_NORMAL.csv")



